---
galaxy_info:
  author: Steve Fulmer
  description: >-
    Deploy Docker containers with networks, volumes, and compose stacks on Unraid
  license: GPL-3.0-or-later
  min_ansible_version: "2.16"
  platforms:
    - name: GenericLinux
      versions:
        - all
  galaxy_tags:
    - unraid
    - docker
    - containers
dependencies: []
