---
galaxy_info:
  author: Steve Fulmer
  description: >-
    Configure Unraid user shares with SMB/NFS access and cache mover settings
  license: GPL-3.0-or-later
  min_ansible_version: "2.16"
  platforms:
    - name: GenericLinux
      versions:
        - all
  galaxy_tags:
    - unraid
    - shares
    - smb
    - nfs
    - cache
dependencies: []
